jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            tfm: net10.0-windows10.0.19041.0
            workload: maui-windows
            artifact: windows-app
          - os: ubuntu-latest
            tfm: net10.0-android
            workload: maui-android
            artifact: android-apk
            tempdir: "/home/runner/work/_temp"
          - os: macos-latest
            tfm: net10.0-ios
            workload: maui-ios
            artifact: ios-ipa
          - os: macos-latest
            tfm: net10.0-maccatalyst
            workload: maui-maccatalyst
            artifact: maccatalyst-app
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Restore
      run: dotnet restore
    - name: Install workload
      run: dotnet workload install ${{ matrix.workload }} --version ${{ env.WORKLOAD_VERSION }}${{ matrix.tempdir && format('--temp-dir {0}', matrix.tempdir) || '' }} --ignore-failed-sources
    - name: Workload restore
      run: dotnet workload restore
    - name: Build ${{ matrix.tfm }}
      run: dotnet build -f ${{ matrix.tfm }} -c Release
    - name: Upload ${{ matrix.artifact }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact }}
        path: bin/Release/${{ matrix.tfm }}/